### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by maaaaqqqq** [maaaaqqqq/protospace-37360#1]
https://protospace-37360.herokuapp.com/

**Comment by wakazo228** [comment]
@maaaaqqqq さん、ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像をクリックすると、該当する詳細ページへ遷移するようにしましょう**
ログアウト状態で一覧表示されている画像をクリックしても、詳細ページへ遷移せずトップページに留まってしまいます。

※プロトタイプ詳細機能に関しては、上記によりログアウト状態でのアクセスが出来ず動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

- [ ] プロトタイプ編集機能において、正しく編集できた場合は、詳細ページへ遷移するようにしましょう
- [ ] ああ
- [ ] ああ




修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by wakazo228** [comment]
@maaaaqqqq さん、ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像をクリックすると、該当する詳細ページへ遷移するようにしましょう**
ログアウト状態で一覧表示されている画像をクリックしても、詳細ページへ遷移せずトップページに留まってしまいます。

- [ ] **ログアウト状態のユーザーであっても、プロトタイプ詳細ページには遷移できるようにしましょう**
プロトタイプ詳細ページに遷移しようとすると、トップページに遷移してしまいます。

※ログアウト状態での詳細ページにおける動作に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

- [ ] **プロトタイプ編集機能において、正しく編集できた場合は、詳細ページへ遷移するようにしましょう**
正しく編集できた場合に、トップページへ遷移してしまいます。

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう**
トップページのユーザー名をクリックすると、ユーザーの詳細ページではなく、プロトタイプの詳細ページに遷移してしまいます。

- [ ] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされるようにしましょう**
現状、他のユーザーのプロトタイプ編集ページに遷移でき、また編集できてしまいます。




修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、新たに修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **ログイン状態のユーザーだけが、投稿ページへ遷移できるようにしましょう**
「New Proto」ボタンを押すと、エラーページへ遷移してしまいます。
<img width="568" alt="スクリーンショット 2022-01-13 12 22 41" src="https://user-images.githubusercontent.com/62644781/149260374-8ce0e2ef-9bc0-4afe-86a2-1dcb6071bc44.png">

**※上記によりプロトタイプが投稿できないため、前回依頼箇所の修正確認ができませんでした。
次回ご提出時に併せて確認させていただきます。**

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、引き続き修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう**
コメントの投稿者名をクリックしたときに正しく遷移しません。（そのプロトタイプを投稿したユーザーの詳細ページに遷移してしまいます。）

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by wakazo228** [comment]
ご提出ありがとうございます！
正常に動作することが確認できました！ **LGTM**です✨
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう(^^)
